// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1nR_ePzO3rpo0LNF61u3fwaKTPLsPJ4',
    appId: '1:824870373289:web:4b58fd13d4d8bcf53866b8',
    messagingSenderId: '824870373289',
    projectId: 'ecosnap-ec791',
    authDomain: 'ecosnap-ec791.firebaseapp.com',
    storageBucket: 'ecosnap-ec791.firebasestorage.app',
    measurementId: 'G-CSTP0783B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOMC6p2X2S_EQWhFVtqWhg7iLvH-gIkGc',
    appId: '1:824870373289:android:b5980b66215880da3866b8',
    messagingSenderId: '824870373289',
    projectId: 'ecosnap-ec791',
    storageBucket: 'ecosnap-ec791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BTO7PRXK0jQIkal9a_dg3hqvFuLf1Q4',
    appId: '1:824870373289:ios:cc0b7c855245fb1d3866b8',
    messagingSenderId: '824870373289',
    projectId: 'ecosnap-ec791',
    storageBucket: 'ecosnap-ec791.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BTO7PRXK0jQIkal9a_dg3hqvFuLf1Q4',
    appId: '1:824870373289:ios:cc0b7c855245fb1d3866b8',
    messagingSenderId: '824870373289',
    projectId: 'ecosnap-ec791',
    storageBucket: 'ecosnap-ec791.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV1nR_ePzO3rpo0LNF61u3fwaKTPLsPJ4',
    appId: '1:824870373289:web:f0e6ba838fe8df693866b8',
    messagingSenderId: '824870373289',
    projectId: 'ecosnap-ec791',
    authDomain: 'ecosnap-ec791.firebaseapp.com',
    storageBucket: 'ecosnap-ec791.firebasestorage.app',
    measurementId: 'G-FPXCYVW1YJ',
  );
}
